---
MicrophoneSettings:
  rate: 16000
  channels: 1
  width: 2
  chunk: 2048
  mic_name: "ReSpeaker 4 Mic Array (UAC1.0)"
  idVendor: 0x2886
  idProduct: 0x0018
---
FileOutput:
  output_dir: "./Output/"
  wave_output: "recording.wav"
  log_output: "log.txt"
  angle_output: "angle.txt"
