---
Recording:
  rate: 16000
  channels: 1
  width: 2
  chunk: 2048
  mic_name: "ReSpeaker 4 Mic Array (UAC1.0)"
  idVendor: 0x2886
  idProduct: 0x0018
  wave_output: "./Output/recording.wav"
  angle_output: "./Output/angle.txt"
  split_output: "./Output/chunk%03d.wav"
  split_length_sec: 30
  overlap_length_sec: 3
  live_split_output: "./Output/split"
---
Logging:
  log_output: "./Output/log.txt"
